# Use an official Python runtime as a parent image
FROM python:3.11

# Set the working directory in the container
WORKDIR /app

# Install necessary system dependencies for Playwright and Xvfb
RUN apt-get update && apt-get install -y \
    libnss3 \
    libnspr4 \
    libdbus-1-3 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdrm2 \
    libxfixes3 \
    libxrandr2 \
    libgbm1 \
    libxkbcommon0 \
    libasound2 \
    libxshmfence1 \
    libglu1-mesa \
    xvfb \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Copy the requirements file into the container at /app
COPY requirements.txt .

# Copy following files and folders into the container

COPY .pytest_cache/ .pytest_cache/
COPY assets/ assets/
COPY config/ config/
COPY modules/ modules/
COPY screenshots/ screenshoots/
COPY test_data/ test_data/
COPY tests/ tests/
COPY pytest.ini .
COPY azure-pipelines-playwright.yml .
COPY conftest.py .
COPY Jenkinsfile .
COPY main.py .
COPY report-headless-false-JsonData.html .
COPY report-headless-true-JsonData.html .
COPY reportbdd.html .
COPY reportdbb.html .
COPY Dockerfile-headless .
COPY Dockerfile-nonheadless .
# COPY External Libraries/ External Libraries/
# COPY Scratches and Consoles/ Scratches and Consoles/


# Install Python dependencies
RUN python -m pip install --upgrade pip && \
    pip install -r requirements.txt && \
    pip install pytest-html

# Install Playwright Browsers with Dependencies
RUN python -m playwright install --with-deps

# Set HEADLESS environment variable to true
ENV HEADLESS=true

# Command to run the tests with headless mode enabled and generate HTML report
# CMD ["pytest", "-v", "-s", "--html=reportbdd.html", "--self-contained-html", "--log-cli-level=INFO"]
# CMD ["sh", "-c", "pytest --html=reportbdd.html --self-contained-html --log-cli-level=INFO && tail -f /dev/null"]
CMD ["sh", "-c", "pytest --html=reportbdd.html --self-contained-html --log-cli-level=INFO"]

